// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinutosProject.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MinutosProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230420041035_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MinutosProject.Models.Auxiliar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Auxiliar");
                });

            modelBuilder.Entity("MinutosProject.Models.Courier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Courier");
                });

            modelBuilder.Entity("MinutosProject.Models.Empresa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("MinutosProject.Models.Envio", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<int>("Auxiliar")
                        .HasColumnName("aux")
                        .HasColumnType("integer");

                    b.Property<int>("Courier")
                        .HasColumnName("courier")
                        .HasColumnType("integer");

                    b.Property<int>("Empresa")
                        .HasColumnName("empresa")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnName("fec_entre")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("HraLlegada")
                        .HasColumnName("hr_llegada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HraSalida")
                        .HasColumnName("hr_salida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Respuesta")
                        .HasColumnName("respuesta")
                        .HasColumnType("text");

                    b.Property<int>("TipoMercaderia")
                        .HasColumnName("mercaderia")
                        .HasColumnType("integer");

                    b.Property<int>("TipoServicio")
                        .HasColumnName("servicio")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Envio");
                });

            modelBuilder.Entity("MinutosProject.Models.TipoMercaderia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("TipoMercaderia");
                });

            modelBuilder.Entity("MinutosProject.Models.TipoServicio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("TipoServicio");
                });
#pragma warning restore 612, 618
        }
    }
}
